packages:
  - fuma
  - datasource
  - packages/**/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: false
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: ^4
  typescript: ^7
  "@types/node": ^24
catalogs:
  react:
    react: '19.2.6'
    react-dom: '19.2.6'
    "@types/react": "^19"
    "@types/react-dom": "^19"
  drizzle:
    drizzle-kit: ^1.0.0-rc.4
    drizzle-orm: 1.0.0-rc.4
  hono:
    hono: ^4.12.18
  tailwindcss:
    "tailwindcss": "^4.3.0"
  fumadocs:
    "@fumadocs/base-ui": ^16.15.17
    "fumadocs-ui": npm:@fumadocs/base-ui@16.15.17
    "fumadocs-core": ^16.15.17
minimumReleaseAgeExclude:
  - tsdown@0.22.1
  - '@cloudflare/workers-types@5.20260930.2'
patchedDependencies:
  fumadocs-core: patches/fumadocs-core.patch
  vinext: patches/vinext.patch

overrides:
  '@types/hast': 3.0.5
  drizzle-orm: 1.0.0-rc.4
