packages:
  - fuma
  - datasource
  - packages/**/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: false
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.1
  zod: ^4
  typescript: ^7
  "@types/node": ^24
  "cf": "^1.0.0-beta.12"
  "@cloudflare/vitest-plugin": "^1.3.6"
  "@cloudflare/vite-plugin": "2.0.0-beta.sha-ad79608dd"
  "@cloudflare/workers-types": latest
catalogs:
  react:
    react: "19.2.6"
    react-dom: "19.2.6"
    "@types/react": "^19"
    "@types/react-dom": "^19"
  drizzle:
    drizzle-kit: ^1.0.0-rc.4
    drizzle-orm: 1.0.0-rc.4
  hono:
    hono: ^4.12.18
  tailwindcss:
    "tailwindcss": "^4.3.3"
    "@tailwindcss/vite": "^4.3.3"
  fumadocs:
    "@fumadocs/base-ui": ^16.15.17
    "fumadocs-ui": npm:@fumadocs/base-ui@16.15.17
    "fumadocs-core": ^16.15.17
minimumReleaseAgeExclude:
  - tsdown@0.22.1
  - "@cloudflare/workers-types@5.20260930.2"
  - "@typescript/typescript-darwin-arm64@7.1.0-dev.20261002.1"
  - "@typescript/typescript-darwin-x64@7.1.0-dev.20261002.1"
  - "@typescript/typescript-linux-arm64@7.1.0-dev.20261002.1"
  - "@typescript/typescript-linux-arm@7.1.0-dev.20261002.1"
  - "@typescript/typescript-linux-x64@7.1.0-dev.20261002.1"
  - "@typescript/typescript-win32-arm64@7.1.0-dev.20261002.1"
  - "@typescript/typescript-win32-x64@7.1.0-dev.20261002.1"
  - typescript@7.1.0-dev.20261002.1
  - vite@8.3.3
patchedDependencies:
  "@fuma-comment/server": patches/@fuma-comment__server.patch
  fumadocs-core: patches/fumadocs-core.patch

overrides:
  "@types/hast": 3.0.5
  drizzle-orm: 1.0.0-rc.4
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
